general {
    hide_cursor = true
    ignore_empy_input = true
}

animations {
    enabled = false
}

background {
    path = screenshot
    blur_passes = 3
}

input-field {
    size = 20%, 5%
    outline_thickness = 3
    fade_on_empty = false
    placeholder_text = Input password...
    fail_text = $PAMFAIL
    inner_color = rgba(0, 0, 0, 0.0)
    font_color = rgba(255, 255, 255, 1.0)
    outer_color = rgba(255, 255, 255, 1.0)
}

# TIME
label {
    text = $TIME
    font_size = 90
    position = 0, -300
    valign = top
}

# DATE
label {
    text = cmd[update:60000] date +"%A, %d %B %Y" # update every 60 seconds
    font_size = 25
    position = 0, -450
    valign = top
}
